apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: {{ .Values.clusterName | quote }}
  {{ if .Values.fluentBitHttpPort }}
  http.server: "On"
  {{ else }}
  http.server: "Off"
  {{ end }}
  http.port: {{ .Values.fluentBitHttpPort | default 2020 | quote }}
  read.head: {{ .Values.fluentBitReadFromHead | quote }}
  {{ if eq .Values.fluentBitReadFromHead "On" }}
  read.tail: "Off"
  {{ else }}
  read.tail: "On"
  {{ end }}
  logs.region: {{ .Values.regionName | quote }}